version: '3'
services:
    mysql: 
        image: mysql:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        restart: unless-stopped    
        volumes:
            - "./data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "root"

